name: Setup account
on:
  workflow_dispatch:
    inputs:
      auth_code:
        description: "Authentication code"
        type: string

env:
  LEGENDARY_CONFIG_PATH: /tmp/legendary

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y_%m_%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Configure legendary credentials cache
        uses: actions/cache@v4
        id: credentials-cache
        with:
          path: /tmp/legendary/user.json
          key: legendary-data-${{ github.run_id }}

      - name: Install legendary
        run: |
          sudo wget -O /bin/legendary https://github.com/derrod/legendary/releases/latest/download/legendary_linux_x64
          sudo chmod +x /bin/legendary

      - name: Authenticate using code
        run: |
          legendary auth --code ${{ inputs.auth_code }}

      - name: Verify login
        run: |
          legendary status > /tmp/_status
          cat /tmp/_status
          ACCOUNT_NAME=$(cat /tmp/_status | grep 'Epic account:' | sed -n -e 's/^Epic account: //p')
          if [ "$ACCOUNT_NAME" = "<not logged in>" ]; then
              echo "Login failed!"
              exit 1
          fi