name: Update metadata
on:
  schedule:
    - cron: 0 */3 * * *
  workflow_dispatch:
    inputs:
      debug_shell:
        description: 'Start debug shell'
        type: boolean
        default: false

env:
  LEGENDARY_CONFIG_PATH: /tmp/legendary

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      skip_update: ${{ steps.version-cache.outputs.cache-hit }}
      version: ${{ steps.version-check.outputs.version }}
    permissions:
      contents: read

    steps:
      - name: Get current date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT
          echo "time=$(/bin/date -u "+%H_%M")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Configure legendary credentials cache
        uses: actions/cache@v4
        with:
          path: '${{ env.LEGENDARY_CONFIG_PATH }}/user.json'
          key: legendary-data-${{ github.run_id }}
          restore-keys: |
            legendary-data-
      
      - name: Account credentials check
        run: |
          if [ ! -f "$LEGENDARY_CONFIG_PATH/user.json" ]; then
            exit 1
          fi

      - name: Install legendary
        run: |
          sudo wget -O /bin/legendary https://github.com/derrod/legendary/releases/latest/download/legendary
          sudo chmod +x /bin/legendary

      - name: Get latest version info
        id: version-check
        run: |
          LATEST_VERSION=$(legendary info Sugar | grep "Latest version: " | sed -n -e 's/^.*Latest version: //p')
          if [ -z "$LATEST_VERSION" ]; then
              echo "Failed to get latest version id!"
              exit 1
          fi
          echo "Latest version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Check if version was already processed
        id: version-cache
        uses: actions/cache@v4
        with:
          path: /tmp/rocket_league_version
          key: game-version-${{ steps.version-check.outputs.version }}

  update:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.skip_update != 'true' }}
    permissions:
      contents: write
    env:
      LEGENDARY_BASE_DIR: /tmp
      # TODO: replace with ${{ env.LEGENDARY_BASE_DIR }}
      GAME_INSTALL_DIR: /tmp/rocketleague

    steps:
      - name: Get current date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT
          echo "time=$(/bin/date -u "+%H_%M")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Configure legendary credentials cache
        uses: actions/cache@v4
        with:
          path: '${{ env.LEGENDARY_CONFIG_PATH }}/user.json'
          key: legendary-data-${{ github.run_id }}
          restore-keys: |
            legendary-data-
      
      - name: Account credentials check
        run: |
          if [ ! -f "$LEGENDARY_CONFIG_PATH/user.json" ]; then
            exit 1
          fi

      - name: Install legendary
        run: |
          sudo wget -O /bin/legendary https://github.com/derrod/legendary/releases/latest/download/legendary
          sudo chmod +x /bin/legendary

      - name: Download Rocket League
        run: legendary install --download-only --skip-dlcs --disable-delta-manifests --base-path "$LEGENDARY_BASE_DIR" --game-folder 'rocketleague' --prefix 'binaries' --prefix 'tagame/legal' --yes Sugar

      - name: Pull repository
        uses: actions/checkout@v4

      - name: Pull previous data
        uses: actions/checkout@v4
        with:
          ref: 'data'
          path: 'data'
      
      - name: Start interactive debug shell
        if: ${{ inputs.debug_shell }}
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true

      - name: Run metadata update
        id: metadata-update
        run: |
          chmod +x ./update-metadata.sh
          ./update-metadata.sh
          echo "${{ needs.check.outputs.version }}" > /tmp/rocket_league_version

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './data'
          message: 'Rocket League "${{ needs.check.outputs.version }}"'
          default_author: github_actions
          tag: 'build/${{ steps.metadata-update.outputs.build_id }}'
      
      - name: Store successful metadata update
        id: version-cache
        uses: actions/cache@v4
        with:
          path: /tmp/rocket_league_version
          key: game-version-${{ steps.version-check.outputs.version }}